name: Deploy

on: [push]

jobs:
  build-image:
    name: build image
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: build image
        run: docker build -t wdinx/mini-project:latest .
      - name: login registry
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: push image
        run: docker push wdinx/mini-project:latest


  deploy:
    runs-on: ubuntu-latest
    needs: build-image
    steps:
      - name: deploy-to-droplets
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          passphrase: ${{ secrets.PASSPRHASE }}
          script: |
            cd ~/
            docker pull wdinx/mini-project:latest
            docker container rm -f mini-project
            docker run -d --name mini-project -p 3000:3000 --env DBHOST=${{ secrets.DBHOST }} --env DBPORT=${{ secrets.DBPORT }} --env DBUSER=${{ secrets.DBUSER }} --env DBPASS=${{ secrets.DBPASS }} --env DBNAME=${{ secrets.DBNAME }} --env BASEURL=${{ secrets.BASEURL }} --env MIDTRANS_KEY=${{ secrets.MIDTRANS_KEY }} --env MIDTRANS_ENV=${{ secrets.MIDTRANS_ENV }} wdinx/mini-project:latest